/*
* DeverseCloudLIB_TMPLDev_v000_.h
*
*  Created on: 2019年5月29日
*      Author: shb
*     version: 1.1
*/
#ifndef __DIVERSECLOUDLIB_TMPL_DEV_V000_H_
#define __DIVERSECLOUDLIB_TMPL_DEV_V000_H_

/*********数据MSGTAG定义******************/
#define	TLV_MSGTAG_DEV_PERIP_OFFLINE	(0x01)//外设掉线	
#define	TLV_MSGTYPE_DEV_PERIP_OFFLINE	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_PERIP_HEARTBEAT	(0x02)//外设心跳			
#define	TLV_MSGTYPE_DEV_PERIP_HEARTBEAT	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_PUMP_SFACETEMP_1	(0x15)//泵表面温度			
#define	TLV_MSGTYPE_DEV_PUMP_SFACETEMP_1	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_PUMP_SFACEAMP_1	(0x16)//泵表面振幅			
#define	TLV_MSGTYPE_DEV_PUMP_SFACEAMP_1	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_CISTERN_PH	(0x17)//PH值			
#define	TLV_MSGTYPE_DEV_CISTERN_PH	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_CISTERN_TBDTY	(0x18)//浊度			
#define	TLV_MSGTYPE_DEV_CISTERN_TBDTY	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_CISTERN_RSDALCL	(0x19)//余氯			
#define	TLV_MSGTYPE_DEV_CISTERN_RSDALCL	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_CISTERN_WATERLEVEL	(0x1A)//水位高度			
#define	TLV_MSGTYPE_DEV_CISTERN_WATERLEVEL	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_CISTERN_INLETPRESSURE	(0x1B)//蓄水池进水口压力			
#define	TLV_MSGTYPE_DEV_CISTERN_INLETPRESSURE	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_CISTERN_OUTLETPRESSURE	(0x1C)//蓄水池出水口压力			
#define	TLV_MSGTYPE_DEV_CISTERN_OUTLETPRESSURE	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_CISTERN_PIPE	(0x1D)//管路流速(瞬时流量)			
#define	TLV_MSGTYPE_DEV_CISTERN_PIPE	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_CISTERN_PIPEACCUMFLOW	(0x1E)//管路累积流量			
#define	TLV_MSGTYPE_DEV_CISTERN_PIPEACCUMFLOW	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_PHENV_TEMP	(0x1F)//环境温度			
#define	TLV_MSGTYPE_DEV_PHENV_TEMP	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_2)//sshort.2	-327.67~327.67
#define	TLV_MSGTAG_DEV_PHENV_HUM	(0x20)//环境湿度			
#define	TLV_MSGTYPE_DEV_PHENV_HUM	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_PHENV_NOISE	(0x21)//环境噪音			
#define	TLV_MSGTYPE_DEV_PHENV_NOISE	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_PHENV_SMOKE	(0x22)//环境烟火感应			
#define	TLV_MSGTYPE_DEV_PHENV_SMOKE	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_PHENV_WATER	(0x23)//环境积水状态			
#define	TLV_MSGTYPE_DEV_PHENV_WATER	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_PHENV_ACCESS	(0x24)//门禁状态			
#define	TLV_MSGTYPE_DEV_PHENV_ACCESS	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_EMETER_VPHASEA	(0x25)//A相电压			
#define	TLV_MSGTYPE_DEV_EMETER_VPHASEA	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_EMETER_VPHASEB	(0x26)//B相电压			
#define	TLV_MSGTYPE_DEV_EMETER_VPHASEB	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_EMETER_VPHASEC	(0x27)//C相电压			
#define	TLV_MSGTYPE_DEV_EMETER_VPHASEC	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_EMETER_CPHASEA	(0x28)//A相电流			
#define	TLV_MSGTYPE_DEV_EMETER_CPHASEA	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_EMETER_CPHASEB	(0x29)//B相电流			
#define	TLV_MSGTYPE_DEV_EMETER_CPHASEB	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_EMETER_CPHASEC	(0x2A)//C相电流			
#define	TLV_MSGTYPE_DEV_EMETER_CPHASEC	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3	0~65.535
#define	TLV_MSGTAG_DEV_EMETER_CT	(0x2B)//CT			
#define	TLV_MSGTYPE_DEV_EMETER_CT	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_0)//ushort.0	0~65535
#define	TLV_MSGTAG_DEV_EMETER_PT	(0x2C)//PT			
#define	TLV_MSGTYPE_DEV_EMETER_PT	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_0)//ushort.0	0~65535
#define	TLV_MSGTAG_DEV_EMETER_FREQ	(0x2D)//频率			
#define	TLV_MSGTYPE_DEV_EMETER_FREQ	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_EMETER_ACTIVEPOWER	(0x2E)//总有功功率			
#define	TLV_MSGTYPE_DEV_EMETER_ACTIVEPOWER	(TLV_MSGPROP_TYPE_SINT|TLV_MSGPROP_DECIMAL_2)//sint.2	-21474836.47~21474836.47
#define	TLV_MSGTAG_DEV_EMETER_REACTIVEPOWER	(0x2F)//总无功功率			
#define	TLV_MSGTYPE_DEV_EMETER_REACTIVEPOWER	(TLV_MSGPROP_TYPE_SINT|TLV_MSGPROP_DECIMAL_2)//sint.2	-21474836.47~21474836.47
#define	TLV_MSGTAG_DEV_EMETER_PF	(0x30)//功率因素总和			
#define	TLV_MSGTYPE_DEV_EMETER_PF	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_3)//sshort.3	-32.767~32.767
#define	TLV_MSGTAG_DEV_EMETER_ACTIVEE	(0x31)//有功电度总和			
#define	TLV_MSGTYPE_DEV_EMETER_ACTIVEE	(TLV_MSGPROP_TYPE_UINT|TLV_MSGPROP_DECIMAL_2)//uint.2	0~42949672.94
#define	TLV_MSGTAG_DEV_EMETER_REACTIVEE	(0x32)//无功电度总和			
#define	TLV_MSGTYPE_DEV_EMETER_REACTIVEE	(TLV_MSGPROP_TYPE_UINT|TLV_MSGPROP_DECIMAL_2)//uint.2	0~42949672.94
#define	TLV_MSGTAG_DEV_WMETER_FLOW	(0x33)//水表流量读数			
#define	TLV_MSGTYPE_DEV_WMETER_FLOW	(TLV_MSGPROP_TYPE_UINT|TLV_MSGPROP_DECIMAL_3)//uint.2	0~42949672.94
#define	TLV_MSGTAG_DEV_WMETER_PRESSURE	(0x34)//水表压力			
#define	TLV_MSGTYPE_DEV_WMETER_PRESSURE	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_3)//ushort.3 	0~65.535
#define	TLV_MSGTAG_DEV_ENV_PM2P5	(0x35)//PM2.5			
#define	TLV_MSGTYPE_DEV_ENV_PM2P5	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_1)//ushort.1	0~6553.5
#define	TLV_MSGTAG_DEV_ENV_PM10	(0x36)//PM10			
#define	TLV_MSGTYPE_DEV_ENV_PM10	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_1)//ushort.1	0~6553.5
#define	TLV_MSGTAG_DEV_ENV_SO2	(0x37)//二氧化硫			
#define	TLV_MSGTYPE_DEV_ENV_SO2	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_ENV_CO	(0x38)//一氧化碳			
#define	TLV_MSGTYPE_DEV_ENV_CO	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_ENV_NO2	(0x39)//二氧化氮			
#define	TLV_MSGTYPE_DEV_ENV_NO2	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_ENV_O3	(0x3A)//臭氧			
#define	TLV_MSGTYPE_DEV_ENV_O3	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_ENV_LM	(0x3B)//光照度			
#define	TLV_MSGTYPE_DEV_ENV_LM	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_1)//ushort.1	0~6553.5
#define	TLV_MSGTAG_DEV_ENV_BP	(0x3C)//大气压			
#define	TLV_MSGTYPE_DEV_ENV_BP	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_1)//ushort.1	0~6553.5
#define	TLV_MSGTAG_DEV_ENV_XACC	(0x3D)//X轴加速度			
#define	TLV_MSGTYPE_DEV_ENV_XACC	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_2)//sshort.2	-327.67~327.67
#define	TLV_MSGTAG_DEV_ENV_YACC	(0x3E)//Y轴加速度			
#define	TLV_MSGTYPE_DEV_ENV_YACC	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_2)//sshort.2	-327.67~327.67
#define	TLV_MSGTAG_DEV_ENV_ZACC	(0x3F)//Z轴加速度			
#define	TLV_MSGTYPE_DEV_ENV_ZACC	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_2)//sshort.2	-327.67~327.67
#define	TLV_MSGTAG_DEV_ENV_LAT	(0x40)//纬度			
#define	TLV_MSGTYPE_DEV_ENV_LAT	(TLV_MSGPROP_TYPE_ULONG|TLV_MSGPROP_DECIMAL_6)//ulong.6	0~4294.967294
#define	TLV_MSGTAG_DEV_ENV_LONG	(0x41)//经度			
#define	TLV_MSGTYPE_DEV_ENV_LONG	(TLV_MSGPROP_TYPE_ULONG|TLV_MSGPROP_DECIMAL_6)//ulong.6	0~4294.967294
#define	TLV_MSGTAG_DEV_ENV_H	(0x42)//海拔高度			
#define	TLV_MSGTYPE_DEV_ENV_H	(TLV_MSGPROP_TYPE_SSHORT|TLV_MSGPROP_DECIMAL_2)//sshort.2	-327.67~327.67
#define	TLV_MSGTAG_DEV_ENV_DIS	(0x43)//红外测距			
#define	TLV_MSGTYPE_DEV_ENV_DIS	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_ENV_STAIO1	(0x44)//IO1状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO1	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO2	(0x45)//IO2状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO2	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO3	(0x46)//IO3状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO3	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO4	(0x47)//IO4状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO4	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO5	(0x48)//IO5状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO5	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO6	(0x49)//IO6状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO6	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO7	(0x4A)//IO7状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO7	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_ENV_STAIO8	(0x4B)//IO8状态			
#define	TLV_MSGTYPE_DEV_ENV_STAIO8	(TLV_MSGPROP_TYPE_UCHAR|TLV_MSGPROP_DECIMAL_0)//uchar.0	0~255
#define	TLV_MSGTAG_DEV_CISTERN_TDS	(0x4C)//水电导率			
#define	TLV_MSGTYPE_DEV_CISTERN_TDS	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_CISTERN_RESERVE1	(0x4D)//保留属性1			
#define	TLV_MSGTYPE_DEV_CISTERN_RESERVE1	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_0)//ushort.0	0~65535
#define	TLV_MSGTAG_DEV_CISTERN_WATERTEMP	(0x4E)//水温度			
#define	TLV_MSGTYPE_DEV_CISTERN_WATERTEMP	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_2)//ushort.2	0~655.35
#define	TLV_MSGTAG_DEV_CISTERN_RESERVE2	(0x4F)//保留属性2			
#define	TLV_MSGTYPE_DEV_CISTERN_RESERVE2	(TLV_MSGPROP_TYPE_USHORT|TLV_MSGPROP_DECIMAL_0)//ushort.0	0~65535

#endif
